# Azure DevOps Pipeline for UAM API
# Enhanced CI/CD pipeline with security scanning and automated deployment

trigger:
  branches:
    include:
      - main
      - develop
  paths:
    exclude:
      - README.md
      - docs/*
      - .gitignore

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure configuration
  azureServiceConnection: 'azure-uam-service-connection'
  resourceGroupName: 'uam-api-rg'
  appServiceName: 'uam-api-$(Build.BuildId)'
  containerRegistry: 'uamcontainerregistry.azurecr.io'
  
  # Build configuration
  nodeVersion: '18.x'
  buildConfiguration: 'production'
  
  # Security and quality gates
  sonarQubeProjectKey: 'uam-api'
  dependencyCheckEnabled: true
  securityScanEnabled: true

stages:
  - stage: 'BuildAndTest'
    displayName: 'Build and Test Application'
    jobs:
      - job: 'Build'
        displayName: 'Build UAM API'
        steps:
          - task: NodeTool@0
            displayName: 'Setup Node.js $(nodeVersion)'
            inputs:
              versionSpec: '$(nodeVersion)'
          
          - task: Cache@2
            displayName: 'Cache npm dependencies'
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: ~/.npm
          
          - script: |
              npm ci
              echo "✅ Dependencies installed successfully"
            displayName: 'Install dependencies'
          
          - script: |
              npm run build
              echo "✅ TypeScript compilation completed"
            displayName: 'Build TypeScript application'
          
          - script: |
              npm run test:ci || echo "⚠️ No tests configured yet"
              echo "✅ Test execution completed"
            displayName: 'Run unit tests'
            continueOnError: true
          
          - task: PublishTestResults@2
            displayName: 'Publish test results'
            condition: always()
            inputs:
              testResultsFormat: 'JUnit'
              testResultsFiles: '**/test-results.xml'
              mergeTestResults: true
              failTaskOnFailedTests: false
          
          - task: PublishCodeCoverageResults@1
            displayName: 'Publish code coverage'
            condition: always()
            inputs:
              codeCoverageTool: 'Istanbul'
              summaryFileLocation: '**/coverage/cobertura-coverage.xml'
              failIfCoverageEmpty: false

  - stage: 'SecurityAndQuality'
    displayName: 'Security and Quality Analysis'
    dependsOn: 'BuildAndTest'
    condition: succeeded()
    jobs:
      - job: 'SecurityScan'
        displayName: 'Security Analysis'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '$(nodeVersion)'
          
          - script: |
              npm ci
              npm audit --audit-level high
              echo "✅ Security audit completed"
            displayName: 'NPM Security Audit'
            continueOnError: true
          
          - script: |
              npx retire --path . --outputformat json --outputpath retire-report.json || true
              echo "✅ Dependency vulnerability scan completed"
            displayName: 'Dependency Vulnerability Scan'
            continueOnError: true

  - stage: 'ContainerBuild'
    displayName: 'Build and Push Container Image'
    dependsOn: 'SecurityAndQuality'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: 'DockerBuild'
        displayName: 'Build Docker Image for Azure'
        steps:
          - task: Docker@2
            displayName: 'Build UAM API Docker image'
            inputs:
              command: 'build'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(containerRegistry)/uam-api:$(Build.BuildId)
                $(containerRegistry)/uam-api:latest
              arguments: '--target production --build-arg NODE_ENV=production'
          
          - task: Docker@2
            displayName: 'Push Docker image to Azure Container Registry'
            inputs:
              command: 'push'
              containerRegistry: '$(azureServiceConnection)'
              repository: 'uam-api'
              tags: |
                $(Build.BuildId)
                latest

  - stage: 'Deploy'
    displayName: 'Deploy to Azure App Service'
    dependsOn: 'ContainerBuild'
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - deployment: 'DeployToAzure'
        displayName: 'Deploy UAM API to Azure'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Deploy to Azure App Service'
                  inputs:
                    azureSubscription: '$(azureServiceConnection)'
                    appType: 'webApp'
                    appName: '$(appServiceName)'
                    package: '$(Pipeline.Workspace)/drop'
                    deploymentMethod: 'auto'
                    runtimeStack: 'NODE|18-lts'
                
                - task: AzureAppServiceSettings@1
                  displayName: 'Configure App Service Settings'
                  inputs:
                    azureSubscription: '$(azureServiceConnection)'
                    appName: '$(appServiceName)'
                    resourceGroupName: '$(resourceGroupName)'
                    appSettings: |
                      [
                        {
                          "name": "NODE_ENV",
                          "value": "production"
                        },
                        {
                          "name": "WEBSITE_NODE_DEFAULT_VERSION",
                          "value": "~18"
                        },
                        {
                          "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                          "value": "true"
                        },
                        {
                          "name": "AZURE_DEPLOYMENT",
                          "value": "true"
                        },
                        {
                          "name": "API_RATE_LIMIT_ENABLED",
                          "value": "true"
                        }
                      ]

  - stage: 'PostDeployment'
    displayName: 'Post-Deployment Verification'
    dependsOn: 'Deploy'
    condition: succeeded()
    jobs:
      - job: 'HealthCheck'
        displayName: 'Verify Deployment Health'
        steps:
          - script: |
              echo "🧪 Testing deployment health..."
              sleep 30
              curl -f https://$(appServiceName).azurewebsites.net/health || exit 1
              echo "✅ Health check passed"
            displayName: 'Health Check'
          
          - script: |
              echo "🔍 Testing API endpoints..."
              curl -f https://$(appServiceName).azurewebsites.net/api/docs || exit 1
              echo "✅ API documentation accessible"
            displayName: 'API Endpoint Verification'
